using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;
namespace RelicRush
{
public sealed class RelicRushGameCompact:MonoBehaviour
{
class T{public string n,c;public Rect r;public T(string n,string c,Rect r){this.n=n;this.c=c;this.r=r;}}
List<T> all=new(),want=new();HashSet<string> found=new();Dictionary<string,Image> hits=new();System.Random rng;Canvas cv;Font font;Sprite px;GameObject menu,game,over;Image room,dark;Text title,scoreT,timeT,targetT,hintT;int round,score,combo,hints;float time,last;bool run,cryptic;
readonly Color32 gold=new(220,170,60,255),cream=new(239,226,193,255),panel=new(20,22,30,246),green=new(54,112,69,255);
void Awake(){rng=new System.Random();Application.targetFrameRate=60;BuildData();BuildUI();ShowMenu();}
void Update(){if(!run)return;time-=Time.deltaTime*(1+Mathf.Max(0,round-8)*.04f);if(combo>0&&Time.time-last>3)combo=0;if(time<=0)End();Hud();}
void BuildData(){string[] n={"KEY","SKULL","HOURGLASS","FEATHER","CANDLE","SCROLL","CRYSTAL","DAGGER","COIN","MUSHROOM","GOBLET","RING","CAT","LANTERN","APPLE","CROWN"};string[] c={"opens what is locked","what remains after flesh","time trapped in glass","once belonged to a bird","a flame on wax","a rolled message","a purple mineral","a short blade","small treasure","a red-capped fungus","a feast cup","finger jewelry","a quiet watcher","portable flame","a red fruit","worn by royalty"};Rect[] r={new(.09f,.70f,.055f,.065f),new(.29f,.43f,.06f,.10f),new(.71f,.69f,.055f,.09f),new(.51f,.16f,.065f,.11f),new(.78f,.34f,.05f,.13f),new(.32f,.10f,.075f,.08f),new(.61f,.17f,.06f,.11f),new(.84f,.14f,.055f,.12f),new(.27f,.19f,.045f,.07f),new(.16f,.31f,.06f,.10f),new(.90f,.41f,.05f,.10f),new(.45f,.33f,.045f,.08f),new(.58f,.34f,.08f,.11f),new(.04f,.39f,.055f,.13f),new(.73f,.10f,.05f,.08f),new(.86f,.78f,.07f,.09f)};for(int i=0;i<n.Length;i++)all.Add(new T(n[i],c[i],r[i]));}
void BuildUI(){var g=new GameObject("Canvas",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster));cv=g.GetComponent<Canvas>();cv.renderMode=RenderMode.ScreenSpaceOverlay;var s=g.GetComponent<CanvasScaler>();s.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;s.referenceResolution=new(1280,720);if(FindFirstObjectByType<EventSystem>()==null)new GameObject("EventSystem",typeof(EventSystem),typeof(StandaloneInputModule));font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");px=Pixel();menu=Root("Menu");var bg=Img(menu.transform,Color.white);bg.sprite=Spr(Art(false));Stretch(bg.rectTransform);var shade=Img(menu.transform,new Color(0,0,0,.42f));Stretch(shade.rectTransform);var box=Panel(menu.transform,new(.10f,.14f),new(.52f,.86f));Txt(box.transform,"RELIC RUSH",60,gold,new(.06f,.70f),new(.94f,.93f));Txt(box.transform,"ENDLESS HIDDEN-OBJECT ROGUELITE",19,cream,new(.06f,.61f),new(.94f,.72f));Txt(box.transform,"Find objects, chain combos, survive harder rounds and chase your best score.",22,cream,new(.09f,.37f),new(.91f,.60f));Btn(box.transform,"START HUNT",new(.18f,.15f),new(.82f,.31f),StartRun,out _);
game=Root("Game");room=Img(game.transform,Color.white);room.rectTransform.anchorMin=new(0,.14f);room.rectTransform.anchorMax=new(1,.88f);room.rectTransform.offsetMin=room.rectTransform.offsetMax=Vector2.zero;var b=room.gameObject.AddComponent<Button>();b.transition=Selectable.Transition.None;b.onClick.AddListener(Wrong);dark=Img(game.transform,new Color(0,0,.02f,.68f));dark.raycastTarget=false;dark.rectTransform.anchorMin=new(0,.14f);dark.rectTransform.anchorMax=new(1,.88f);dark.rectTransform.offsetMin=dark.rectTransform.offsetMax=Vector2.zero;var top=Panel(game.transform,new(.01f,.89f),new(.99f,.99f));title=Txt(top.transform,"ROOM",22,gold,new(.02f,.05f),new(.42f,.95f));scoreT=Txt(top.transform,"SCORE",22,cream,new(.45f,.05f),new(.70f,.95f));timeT=Txt(top.transform,"00:00",28,gold,new(.74f,.05f),new(.97f,.95f));var bot=Panel(game.transform,new(.01f,.01f),new(.99f,.13f));targetT=Txt(bot.transform,"FIND",18,cream,new(.02f,.05f),new(.80f,.95f));Btn(bot.transform,"HINT",new(.82f,.15f),new(.98f,.85f),Hint,out hintT);
over=Root("Over");var os=Img(over.transform,new Color(.01f,.01f,.02f,.95f));Stretch(os.rectTransform);var ob=Panel(over.transform,new(.30f,.22f),new(.70f,.78f));Txt(ob.transform,"RUN OVER",48,gold,new(.08f,.70f),new(.92f,.91f));var result=Txt(ob.transform,"",28,cream,new(.08f,.35f),new(.92f,.68f));result.name="Result";Btn(ob.transform,"PLAY AGAIN",new(.18f,.14f),new(.82f,.29f),StartRun,out _);}
void ShowMenu(){menu.SetActive(true);game.SetActive(false);over.SetActive(false);run=false;}void StartRun(){menu.SetActive(false);over.SetActive(false);game.SetActive(true);round=1;score=combo=0;hints=3;Begin();}
void Begin(){run=true;found.Clear();want.Clear();combo=0;cryptic=round>=3&&round%3==0;dark.gameObject.SetActive(round>=4&&round%4==0);bool tavern=round%2==0;room.sprite=Spr(Art(tavern));title.text=$"ROOM {round} — {(tavern?"SMUGGLER'S TAVERN":"ALCHEMIST WORKSHOP")}";int count=Mathf.Clamp(3+(round-1)/2,3,8);want.AddRange(all.OrderBy(x=>rng.Next()).Take(count));time=Mathf.Max(18,42-round)+2;MakeHits();Targets();Hud();}
void MakeHits(){foreach(Transform ch in room.transform)if(ch.gameObject!=dark.gameObject)Destroy(ch.gameObject);hits.Clear();foreach(var t in all){var g=new GameObject("Hit "+t.n,typeof(RectTransform),typeof(Image),typeof(Button));g.transform.SetParent(room.transform,false);var r=g.GetComponent<RectTransform>();r.anchorMin=new(t.r.x,1-t.r.y-t.r.height);r.anchorMax=new(t.r.x+t.r.width,1-t.r.y);r.offsetMin=r.offsetMax=Vector2.zero;var im=g.GetComponent<Image>();im.color=new(1,1,1,.001f);var bt=g.GetComponent<Button>();bt.transition=Selectable.Transition.None;bt.onClick.AddListener(()=>Tap(t));hits[t.n]=im;}}
void Tap(T t){if(!run)return;if(want.Contains(t)&&!found.Contains(t.n)){found.Add(t.n);combo++;last=Time.time;score+=100+Mathf.Max(0,combo-1)*20;Targets();if(found.Count==want.Count){score+=Mathf.CeilToInt(time)*5;round++;Begin();}}else Wrong();}
void Wrong(){if(!run)return;combo=0;time=Mathf.Max(0,time-2.5f);}void Hint(){if(!run||hints<=0)return;var left=want.Where(t=>!found.Contains(t.n)).ToList();if(left.Count==0)return;hints--;var t=left[rng.Next(left.Count)];hits[t.n].color=new(1,.85f,.1f,.55f);Invoke(nameof(ClearHint),1);Hud();}void ClearHint(){foreach(var i in hits.Values)i.color=new(1,1,1,.001f);}
void End(){run=false;int best=Mathf.Max(PlayerPrefs.GetInt("RelicRush.Best",0),score);PlayerPrefs.SetInt("RelicRush.Best",best);PlayerPrefs.Save();game.SetActive(false);over.SetActive(true);over.GetComponentsInChildren<Text>(true).First(x=>x.name=="Result").text=$"FINAL SCORE\n{score:N0}\n\nROOM {round}\nBEST {best:N0}";}
void Targets(){targetT.text=(cryptic?"SOLVE: ":"FIND: ")+string.Join("  •  ",want.Select(t=>(found.Contains(t.n)?"[FOUND] ":"")+(cryptic?t.c:t.n)));}void Hud(){if(!game.activeSelf)return;scoreT.text=$"SCORE {score:N0}  COMBO x{1+Mathf.Max(0,combo-1)*.18f:0.00}";int s=Mathf.CeilToInt(time);timeT.text=$"{s/60:00}:{s%60:00}";hintT.text=$"HINT x{hints}";}
GameObject Root(string n)=>Rect(n,cv.transform,Vector2.zero,Vector2.one).gameObject;RectTransform Rect(string n,Transform p,Vector2 a,Vector2 b){var g=new GameObject(n,typeof(RectTransform));g.transform.SetParent(p,false);var r=g.GetComponent<RectTransform>();r.anchorMin=a;r.anchorMax=b;r.offsetMin=r.offsetMax=Vector2.zero;return r;}Sprite Pixel(){var t=new Texture2D(1,1);t.SetPixel(0,0,Color.white);t.Apply();return Spr(t);}Sprite Spr(Texture2D t)=>Sprite.Create(t,new Rect(0,0,t.width,t.height),new(.5f,.5f),100);Image Img(Transform p,Color c){var g=new GameObject("Image",typeof(RectTransform),typeof(Image));g.transform.SetParent(p,false);var i=g.GetComponent<Image>();i.sprite=px;i.color=c;return i;}GameObject Panel(Transform p,Vector2 a,Vector2 b){var o=Img(p,gold);o.rectTransform.anchorMin=a;o.rectTransform.anchorMax=b;o.rectTransform.offsetMin=o.rectTransform.offsetMax=Vector2.zero;var i=Img(o.transform,panel);Stretch(i.rectTransform);i.rectTransform.offsetMin=new(3,3);i.rectTransform.offsetMax=new(-3,-3);return i.gameObject;}Text Txt(Transform p,string v,int size,Color c,Vector2 a,Vector2 b){var g=new GameObject("Text",typeof(RectTransform),typeof(Text));g.transform.SetParent(p,false);var r=g.GetComponent<RectTransform>();r.anchorMin=a;r.anchorMax=b;r.offsetMin=r.offsetMax=Vector2.zero;var t=g.GetComponent<Text>();t.font=font;t.text=v;t.fontSize=size;t.color=c;t.alignment=TextAnchor.MiddleCenter;t.horizontalOverflow=HorizontalWrapMode.Wrap;t.verticalOverflow=VerticalWrapMode.Overflow;return t;}Button Btn(Transform p,string label,Vector2 a,Vector2 b,Action act,out Text tx){var im=Img(p,green);im.rectTransform.anchorMin=a;im.rectTransform.anchorMax=b;im.rectTransform.offsetMin=im.rectTransform.offsetMax=Vector2.zero;var bt=im.gameObject.AddComponent<Button>();bt.onClick.AddListener(()=>act());tx=Txt(im.transform,label,19,cream,new(.03f,.05f),new(.97f,.95f));return bt;}static void Stretch(RectTransform r){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;}
Texture2D Art(bool tavern){const int W=320,H=180;var t=new Texture2D(W,H,TextureFormat.RGBA32,false);t.filterMode=FilterMode.Point;var p=new Color32[W*H];Color32 outl=new(19,14,18,255),stone=new(42,38,59,255),stone2=new(62,50,74,255),wood=new(91,53,31,255),wood2=new(125,72,38,255),g=new(211,151,47,255),pur=new(108,56,145,255),blu=new(46,96,131,255),gr=new(56,109,69,255),re=new(150,56,50,255),cr=new(220,198,150,255);for(int y=0;y<H;y++)for(int x=0;x<W;x++)p[y*W+x]=tavern?new Color32(46,31,31,255):stone;void R(int x,int y,int w,int h,Color32 c){for(int yy=Mathf.Max(0,y);yy<Mathf.Min(H,y+h);yy++)for(int xx=Mathf.Max(0,x);xx<Mathf.Min(W,x+w);xx++)p[yy*W+xx]=c;}void O(int x,int y,int w,int h,Color32 c){R(x-1,y-1,w+2,h+2,outl);R(x,y,w,h,c);}for(int y=0;y<120;y+=12)for(int x=(y/12%2)*8;x<W;x+=24){R(x,y,22,10,((x+y)/12)%2==0?stone:stone2);R(x,y+9,22,1,outl);}R(0,120,W,60,tavern?new Color32(68,40,27,255):new Color32(49,31,33,255));for(int x=0;x<W;x+=18)R(x,120,2,60,outl);O(125,15,70,48,new(25,43,62,255));R(129,19,62,40,new(42,75,99,255));R(159,19,3,40,outl);R(129,38,62,3,outl);for(int sy=64;sy<116;sy+=23){O(15,sy,115,5,wood2);O(205,sy,100,5,wood2);for(int i=0;i<9;i++){int x=22+i*11,h=8+i%4*3;O(x,sy-h,6,h,i%3==0?gr:i%3==1?pur:blu);O(212+i*10,sy-10-i%3*3,6,10+i%3*3,i%2==0?pur:g);}}O(68,128,186,34,wood);R(74,134,174,22,wood2);O(146,119,28,19,new(45,45,50,255));R(151,113,18,7,new(70,63,75,255));R(155,109,10,4,pur);O(28,48,13,5,g);O(89,82,13,11,cr);O(224,45,7,14,g);O(162,139,11,8,pur);O(249,94,6,18,cr);O(103,149,19,5,cr);O(270,141,16,4,new(164,168,177,255));O(69,143,7,7,g);O(52,108,12,10,re);O(287,86,8,12,g);O(141,100,8,7,g);O(187,97,18,11,new(52,45,41,255));O(10,86,10,18,g);O(233,149,9,8,re);O(275,31,18,12,g);for(int i=0;i<110;i++)R((i*47+13)%W,(i*29+7)%120,1,1,i%2==0?new Color32(88,76,98,255):new Color32(35,31,48,255));t.SetPixels32(p);t.Apply();return t;}
}
}
