using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace RelicRush
{
    public sealed class RelicRushGameCompact : MonoBehaviour
    {
        sealed class Obj { public string name, clue; public Rect r; public Obj(string n,string c,Rect rr){name=n;clue=c;r=rr;} }
        readonly Color32 panel=new(20,22,30,245), gold=new(218,170,62,255), cream=new(238,224,190,255), green=new(55,112,70,255), red=new(145,55,62,255);
        readonly List<Obj> objects=new(); readonly List<Obj> targets=new(); readonly HashSet<string> found=new(); readonly Dictionary<string,Button> hitButtons=new();
        Canvas canvas; Font font; Sprite white; Image roomImage,darkOverlay; Text roomT,scoreT,timeT,comboT,targetT,modT,hintT; GameObject menu,game,upgrade,over,hitRoot; System.Random rng;
        int round,score,combo,best,hints,bonusTime; float timer,lastFind,comboPower=.18f; bool playing,locked,cryptic,dark;
        void Awake(){rng=new System.Random(Environment.TickCount);Application.targetFrameRate=60;Screen.orientation=ScreenOrientation.LandscapeLeft;BuildObjects();BuildUI();ShowMenu();}
        void Update(){if(!playing||locked)return;timer-=Time.unscaledDeltaTime*(1f+Mathf.Max(0,round-8)*.035f);if(combo>0&&Time.unscaledTime-lastFind>3f)combo=0;if(timer<=0){timer=0;EndRun();}UpdateHud();}
        void BuildObjects(){objects.AddRange(new[]{
            new Obj("KEY","opens what is locked",new Rect(.09f,.70f,.055f,.065f)),new Obj("SKULL","what remains after the flesh is gone",new Rect(.29f,.43f,.06f,.10f)),
            new Obj("HOURGLASS","time trapped between glass",new Rect(.71f,.69f,.055f,.09f)),new Obj("FEATHER","once belonged to a bird",new Rect(.51f,.16f,.065f,.11f)),
            new Obj("CANDLE","a small flame on wax",new Rect(.78f,.34f,.05f,.13f)),new Obj("SCROLL","a rolled message",new Rect(.32f,.10f,.075f,.08f)),
            new Obj("CRYSTAL","a purple faceted mineral",new Rect(.61f,.17f,.06f,.11f)),new Obj("DAGGER","a short blade",new Rect(.84f,.14f,.055f,.12f)),
            new Obj("COIN","a small piece of treasure",new Rect(.27f,.19f,.045f,.07f)),new Obj("MUSHROOM","a red-capped fungus",new Rect(.16f,.31f,.06f,.10f)),
            new Obj("GOBLET","a cup fit for a feast",new Rect(.90f,.41f,.05f,.10f)),new Obj("RING","jewelry worn on a finger",new Rect(.45f,.33f,.045f,.08f)),
            new Obj("CAT","a quiet four-legged watcher",new Rect(.58f,.34f,.08f,.11f)),new Obj("LANTERN","carries a portable flame",new Rect(.04f,.39f,.055f,.13f)),
            new Obj("APPLE","a red fruit",new Rect(.73f,.10f,.05f,.08f)),new Obj("CROWN","worn by royalty",new Rect(.86f,.78f,.07f,.09f))});}
        void BuildUI(){var cgo=new GameObject("Relic Rush Canvas",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster));DontDestroyOnLoad(cgo);canvas=cgo.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;var sc=cgo.GetComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1280,720);sc.matchWidthOrHeight=.5f;if(FindFirstObjectByType<EventSystem>()==null){var e=new GameObject("EventSystem",typeof(EventSystem),typeof(StandaloneInputModule));DontDestroyOnLoad(e);}font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");white=White();
            menu=Rect("Menu",canvas.transform,Vector2.zero,Vector2.one).gameObject;var mb=Img(menu.transform,Art.Make(false),Color.white);Stretch(mb.rectTransform);var shade=Img(menu.transform,white,new Color(0,0,0,.38f));Stretch(shade.rectTransform);var box=Panel(menu.transform,new Vector2(.08f,.13f),new Vector2(.48f,.87f));Txt(box.transform,"RELIC RUSH",58,gold,FontStyle.Bold,TextAnchor.MiddleCenter,new Vector2(.07f,.73f),new Vector2(.93f,.94f));Txt(box.transform,"ENDLESS HIDDEN-OBJECT ROGUELITE",18,cream,FontStyle.Bold,TextAnchor.MiddleCenter,new Vector2(.06f,.64f),new Vector2(.94f,.74f));Txt(box.transform,"Search dense pixel-art rooms. Chain fast finds, survive harder modifiers, choose upgrades, and chase a new best score.",21,cream,FontStyle.Normal,TextAnchor.UpperCenter,new Vector2(.08f,.38f),new Vector2(.92f,.62f));Btn(box.transform,"START HUNT",new Vector2(.16f,.16f),new Vector2(.84f,.32f),green,StartRun,out _);var info=Panel(menu.transform,new Vector2(.58f,.18f),new Vector2(.92f,.82f));Txt(info.transform,"DEMO FEATURES",28,gold,FontStyle.Bold,TextAnchor.MiddleCenter,new Vector2(.08f,.82f),new Vector2(.92f,.95f));Txt(info.transform,"• 2 detailed pixel-art rooms\n\n• Random target lists\n\n• Timer + wrong-tap penalty\n\n• Combo scoring\n\n• Cryptic clue rounds\n\n• Darkness rounds\n\n• Roguelite upgrades\n\n• Hint powerup\n\n• Persistent high score",20,cream,FontStyle.Normal,TextAnchor.UpperLeft,new Vector2(.11f,.08f),new Vector2(.9f,.8f));
            game=Rect("Game",canvas.transform,Vector2.zero,Vector2.one).gameObject;roomImage=Img(game.transform,null,Color.white);roomImage.rectTransform.anchorMin=new Vector2(0,.13f);roomImage.rectTransform.anchorMax=new Vector2(1,.88f);roomImage.rectTransform.offsetMin=roomImage.rectTransform.offsetMax=Vector2.zero;var bgbtn=roomImage.gameObject.AddComponent<Button>();bgbtn.transition=Selectable.Transition.None;bgbtn.onClick.AddListener(WrongTap);hitRoot=Rect("Hotspots",roomImage.transform,Vector2.zero,Vector2.one).gameObject;darkOverlay=Img(game.transform,white,new Color(0,0,.03f,.68f));darkOverlay.raycastTarget=false;darkOverlay.rectTransform.anchorMin=new Vector2(0,.13f);darkOverlay.rectTransform.anchorMax=new Vector2(1,.88f);darkOverlay.rectTransform.offsetMin=darkOverlay.rectTransform.offsetMax=Vector2.zero;var top=Panel(game.transform,new Vector2(.01f,.89f),new Vector2(.99f,.99f));roomT=Txt(top.transform,"ROOM",22,gold,FontStyle.Bold,TextAnchor.MiddleLeft,new Vector2(.02f,.05f),new Vector2(.26f,.95f));scoreT=Txt(top.transform,"SCORE",22,cream,FontStyle.Bold,TextAnchor.MiddleCenter,new Vector2(.30f,.05f),new Vector2(.52f,.95f));comboT=Txt(top.transform,"COMBO",20,cream,FontStyle.Bold,TextAnchor.MiddleCenter,new Vector2(.53f,.05f),new Vector2(.72f,.95f));timeT=Txt(top.transform,"00:00",30,gold,FontStyle.Bold,TextAnchor.MiddleRight,new Vector2(.75f,.05f),new Vector2(.97f,.95f));var bot=Panel(game.transform,new Vector2(.01f,.01f),new Vector2(.99f,.12f));targetT=Txt(bot.transform,"FIND",18,cream,FontStyle.Bold,TextAnchor.MiddleLeft,new Vector2(.02f,.08f),new Vector2(.68f,.92f));modT=Txt(bot.transform,"STANDARD",16,gold,FontStyle.Bold,TextAnchor.MiddleCenter,new Vector2(.68f,.08f),new Vector2(.81f,.92f));Btn(bot.transform,"HINT",new Vector2(.82f,.12f),new Vector2(.98f,.88f),new Color32(36,66,95,255),UseHint,out hintT);
            upgrade=Rect("Upgrade",canvas.transform,Vector2.zero,Vector2.one).gameObject;var us=Img(upgrade.transform,white,new Color(.01f,.01f,.02f,.94f));Stretch(us.rectTransform);var ub=Panel(upgrade.transform,new Vector2(.16f,.18f),new Vector2(.84f,.82f));Txt(ub.transform,"CHOOSE AN UPGRADE",34,gold,FontStyle.Bold,TextAnchor.MiddleCenter,new Vector2(.08f,.78f),new Vector2(.92f,.94f));MakeUpgrade(ub.transform,"POCKET WATCH","+5 seconds every room",new Vector2(.04f,.18f),()=>bonusTime+=5);MakeUpgrade(ub.transform,"DETECTIVE LENS","+2 hint charges",new Vector2(.355f,.18f),()=>hints+=2);MakeUpgrade(ub.transform,"COMBO CHAIN","stronger combo scoring",new Vector2(.67f,.18f),()=>comboPower+=.08f);
            over=Rect("Game Over",canvas.transform,Vector2.zero,Vector2.one).gameObject;var os=Img(over.transform,white,new Color(.01f,.01f,.02f,.94f));Stretch(os.rectTransform);var ob=Panel(over.transform,new Vector2(.28f,.18f),new Vector2(.72f,.82f));Txt(ob.transform,"RUN OVER",46,red,FontStyle.Bold,TextAnchor.MiddleCenter,new Vector2(.08f,.72f),new Vector2(.92f,.91f));var result=Txt(ob.transform,"",28,cream,FontStyle.Bold,TextAnchor.MiddleCenter,new Vector2(.08f,.35f),new Vector2(.92f,.7f));result.name="Result";Btn(ob.transform,"PLAY AGAIN",new Vector2(.18f,.16f),new Vector2(.82f,.30f),green,StartRun,out _);Btn(ob.transform,"MAIN MENU",new Vector2(.18f,.04f),new Vector2(.82f,.14f),new Color32(35,48,66,255),ShowMenu,out _);}
        void MakeUpgrade(Transform p,string title,string desc,Vector2 min,Action take){var card=Panel(p,min,new Vector2(min.x+.285f,.66f));Txt(card.transform,title,20,gold,FontStyle.Bold,TextAnchor.MiddleCenter,new Vector2(.07f,.72f),new Vector2(.93f,.92f));Txt(card.transform,desc,18,cream,FontStyle.Normal,TextAnchor.UpperCenter,new Vector2(.08f,.38f),new Vector2(.92f,.68f));Btn(card.transform,"TAKE",new Vector2(.16f,.10f),new Vector2(.84f,.30f),green,()=>{take();round++;upgrade.SetActive(false);game.SetActive(true);BeginRound();},out _);}
        void ShowMenu(){playing=false;locked=false;menu.SetActive(true);game.SetActive(false);upgrade.SetActive(false);over.SetActive(false);} void StartRun(){menu.SetActive(false);over.SetActive(false);game.SetActive(true);upgrade.SetActive(false);round=1;score=combo=bonusTime=0;hints=2;comboPower=.18f;BeginRound();}
        void BeginRound(){playing=true;locked=false;found.Clear();targets.Clear();combo=0;cryptic=round>=3&&round%3==0;dark=round>=4&&round%4==0;darkOverlay.gameObject.SetActive(dark);bool tavern=round%2==0;var tex=Art.Make(tavern);roomImage.sprite=Sprite.Create(tex,new Rect(0,0,tex.width,tex.height),new Vector2(.5f,.5f),100);roomT.text=$"ROOM {round} — {(tavern?"SMUGGLER'S TAVERN":"ALCHEMIST WORKSHOP")}";int count=Mathf.Clamp(3+(round-1)/2,3,8);targets.AddRange(objects.OrderBy(_=>rng.Next()).Take(count));timer=Mathf.Max(20,42-(round-1)*1.15f)+bonusTime;BuildHits();RefreshTargets();UpdateHud();}
        void BuildHits(){foreach(Transform c in hitRoot.transform)Destroy(c.gameObject);hitButtons.Clear();foreach(var o in objects){var go=new GameObject("Hit "+o.name,typeof(RectTransform),typeof(Image),typeof(Button));go.transform.SetParent(hitRoot.transform,false);var rt=go.GetComponent<RectTransform>();rt.anchorMin=new Vector2(o.r.x,1-o.r.y-o.r.height);rt.anchorMax=new Vector2(o.r.x+o.r.width,1-o.r.y);rt.offsetMin=rt.offsetMax=Vector2.zero;var im=go.GetComponent<Image>();im.color=new Color(1,1,1,.001f);var b=go.GetComponent<Button>();b.transition=Selectable.Transition.None;b.onClick.AddListener(()=>Tap(o));hitButtons[o.name]=b;}}
        void Tap(Obj o){if(!playing||locked)return;if(targets.Contains(o)&&!found.Contains(o.name)){found.Add(o.name);combo++;lastFind=Time.unscaledTime;score+=Mathf.RoundToInt(100*(1+(combo-1)*comboPower));RefreshTargets();if(found.Count==targets.Count)ClearRound();}else WrongTap();} void WrongTap(){if(!playing||locked)return;combo=0;timer=Mathf.Max(0,timer-2.5f);} void UseHint(){if(!playing||locked||hints<=0)return;var left=targets.Where(x=>!found.Contains(x.name)).ToList();if(left.Count==0)return;hints--;var o=left[rng.Next(left.Count)];if(hitButtons.TryGetValue(o.name,out var b)){b.GetComponent<Image>().color=new Color(1,.82f,.15f,.5f);Invoke(nameof(ClearHint),1f);}UpdateHud();} void ClearHint(){foreach(var b in hitButtons.Values)b.GetComponent<Image>().color=new Color(1,1,1,.001f);}
        void ClearRound(){locked=true;playing=false;score+=Mathf.CeilToInt(timer)*5;if(round%2==0){game.SetActive(false);upgrade.SetActive(true);}else{round++;BeginRound();}} void EndRun(){playing=false;locked=true;best=Mathf.Max(PlayerPrefs.GetInt("RelicRush.Best",0),score);PlayerPrefs.SetInt("RelicRush.Best",best);PlayerPrefs.Save();game.SetActive(false);over.SetActive(true);var t=over.GetComponentsInChildren<Text>(true).First(x=>x.name=="Result");t.text=$"FINAL SCORE\n{score:N0}\n\nROOM REACHED  {round}\nBEST  {best:N0}";}
        void RefreshTargets(){targetT.text=(cryptic?"SOLVE & FIND:  ":"FIND:  ")+string.Join("   •   ",targets.Select(x=>found.Contains(x.name)?"[FOUND] "+(cryptic?x.clue:x.name):(cryptic?x.clue:x.name)));} void UpdateHud(){if(!game.activeSelf)return;scoreT.text=$"SCORE  {score:N0}";int s=Mathf.CeilToInt(timer);timeT.text=$"{s/60:00}:{s%60:00}";comboT.text=$"COMBO x{1+Mathf.Max(0,combo-1)*comboPower:0.00}";modT.text=cryptic&&dark?"CRYPTIC + DARK":cryptic?"CRYPTIC":dark?"DARKNESS":"STANDARD";hintT.text=$"HINT x{hints}";}
        Sprite White(){var t=new Texture2D(1,1);t.SetPixel(0,0,Color.white);t.Apply();return Sprite.Create(t,new Rect(0,0,1,1),new Vector2(.5f,.5f),1);} RectTransform Rect(string n,Transform p,Vector2 a,Vector2 b){var g=new GameObject(n,typeof(RectTransform));g.transform.SetParent(p,false);var r=g.GetComponent<RectTransform>();r.anchorMin=a;r.anchorMax=b;r.offsetMin=r.offsetMax=Vector2.zero;return r;} Image Img(Transform p,Texture2D tex,Color c){Sprite s=tex==null?null:Sprite.Create(tex,new Rect(0,0,tex.width,tex.height),new Vector2(.5f,.5f),100);return Img(p,s,c);} Image Img(Transform p,Sprite s,Color c){var g=new GameObject("Image",typeof(RectTransform),typeof(Image));g.transform.SetParent(p,false);var i=g.GetComponent<Image>();i.sprite=s;i.color=c;return i;} GameObject Panel(Transform p,Vector2 a,Vector2 b){var o=Img(p,white,gold);o.rectTransform.anchorMin=a;o.rectTransform.anchorMax=b;o.rectTransform.offsetMin=o.rectTransform.offsetMax=Vector2.zero;var i=Img(o.transform,white,panel);Stretch(i.rectTransform);i.rectTransform.offsetMin=new Vector2(3,3);i.rectTransform.offsetMax=new Vector2(-3,-3);return i.gameObject;} Text Txt(Transform p,string v,int sz,Color c,FontStyle st,TextAnchor al,Vector2 a,Vector2 b){var g=new GameObject("Text",typeof(RectTransform),typeof(Text));g.transform.SetParent(p,false);var r=g.GetComponent<RectTransform>();r.anchorMin=a;r.anchorMax=b;r.offsetMin=r.offsetMax=Vector2.zero;var t=g.GetComponent<Text>();t.font=font;t.text=v;t.fontSize=sz;t.color=c;t.fontStyle=st;t.alignment=al;t.horizontalOverflow=HorizontalWrapMode.Wrap;t.verticalOverflow=VerticalWrapMode.Overflow;return t;} Button Btn(Transform p,string label,Vector2 a,Vector2 b,Color c,Action act,out Text txt){var g=Img(p,white,c);g.rectTransform.anchorMin=a;g.rectTransform.anchorMax=b;g.rectTransform.offsetMin=g.rectTransform.offsetMax=Vector2.zero;var bt=g.gameObject.AddComponent<Button>();bt.targetGraphic=g;bt.onClick.AddListener(()=>act());txt=Txt(g.transform,label,19,cream,FontStyle.Bold,TextAnchor.MiddleCenter,new Vector2(.03f,.05f),new Vector2(.97f,.95f));return bt;} static void Stretch(RectTransform r){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;}
        static class Art
        {
            static readonly Color32 outline=new(20,14,18,255),stone=new(41,38,58,255),stone2=new(59,49,72,255),wood=new(82,49,32,255),wood2=new(120,70,38,255),gold=new(211,151,47,255),purple=new(105,55,142,255),blue=new(45,94,128,255),green=new(55,105,67,255),red=new(147,54,48,255),cream=new(216,194,148,255);
            public static Texture2D Make(bool tavern){const int W=320,H=180;var t=new Texture2D(W,H,TextureFormat.RGBA32,false);t.filterMode=FilterMode.Point;var p=new Color32[W*H];for(int y=0;y<H;y++)for(int x=0;x<W;x++)p[y*W+x]=tavern?new Color32(44,31,31,255):stone;void R(int x,int y,int w,int h,Color32 c){for(int yy=Mathf.Max(0,y);yy<Mathf.Min(H,y+h);yy++)for(int xx=Mathf.Max(0,x);xx<Mathf.Min(W,x+w);xx++)p[yy*W+xx]=c;}void O(int x,int y,int w,int h,Color32 c){R(x-1,y-1,w+2,h+2,outline);R(x,y,w,h,c);}for(int y=0;y<120;y+=12)for(int x=(y/12%2)*8;x<W;x+=24){R(x,y,22,10,((x+y)/12)%2==0?stone:stone2);R(x,y+9,22,1,outline);}R(0,120,W,60,tavern?new Color32(65,39,27,255):new Color32(48,31,32,255));for(int x=0;x<W;x+=18)R(x,120,2,60,outline);O(125,15,70,48,new Color32(25,43,62,255));R(129,19,62,40,new Color32(41,73,96,255));R(159,19,3,40,outline);R(129,38,62,3,outline);R(135,23,12,2,new Color32(180,197,198,255));for(int sy=64;sy<116;sy+=23){O(15,sy,115,5,wood2);O(205,sy,100,5,wood2);for(int i=0;i<9;i++){int bx=22+i*11,h=8+(i%4)*3;O(bx,sy-h,h/2+4,h,(i%3==0)?green:(i%3==1?purple:blue));int bx2=212+i*10;O(bx2,sy-10-(i%3)*3,6,10+(i%3)*3,(i%2==0)?purple:gold);}}O(68,128,186,34,wood);R(74,134,174,22,wood2);for(int x=85;x<240;x+=28)R(x,136,2,18,outline);O(18,132,36,26,new Color32(53,43,35,255));O(264,126,42,32,new Color32(59,42,34,255));O(146,119,28,19,new Color32(45,45,50,255));R(151,113,18,7,new Color32(70,63,75,255));R(155,109,10,4,purple);R(157,106,6,3,new Color32(181,82,194,255));O(28,48,13,5,gold);R(38,49,6,3,gold);O(89,82,13,11,cream);R(92,79,7,4,cream);R(93,86,2,2,outline);R(98,86,2,2,outline);O(224,45,7,14,gold);R(226,48,3,8,cream);O(162,139,11,8,purple);R(165,134,5,5,new Color32(176,86,205,255));O(249,94,6,18,cream);R(250,91,4,5,gold);O(103,149,19,5,cream);O(270,141,16,4,new Color32(164,168,177,255));R(270,145,5,2,wood2);O(69,143,7,7,gold);O(52,108,12,10,red);R(55,105,6,4,cream);O(287,86,8,12,gold);O(141,100,8,7,gold);R(144,101,2,2,outline);O(187,97,18,11,new Color32(52,45,41,255));R(192,94,8,4,new Color32(72,60,50,255));O(10,86,10,18,gold);R(13,89,4,10,new Color32(226,126,46,255));O(233,149,9,8,red);R(235,146,5,4,green);O(275,31,18,12,gold);R(279,27,3,6,gold);R(287,27,3,6,gold);R(283,25,3,7,gold);for(int i=0;i<90;i++){int x=(i*47+13)%W,y=(i*29+7)%H;if(y<120)R(x,y,1,1,(i%2==0)?new Color32(86,74,96,255):new Color32(35,31,48,255));}t.SetPixels32(p);t.Apply();return t;}
        }
    }
}
